backtraces_path = "/var/log/neovide_backtraces.log" # see below for the default platform specific location
fork = false
frame = "full"
idle = true
maximized = true
mouse-cursor-icon = "arrow"
# neovim-bin = "/usr/bin/nvim"                        # in reality found dynamically on $PATH if unset
no-multigrid = false
srgb = false
tabs = true
theme = "auto"
title-hidden = true
vsync = true
wsl = false

[font]
normal = [
  "UDEV Gothic 35NFLG",
  "Symbols Nerd Font Mono",
] # Will use the bundled Fira Code Nerd Font by default
size = 13.0
