[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

# color
# [colors.bright]
# black = "0x6b7089"
# blue = "0x91acd1"
# cyan = "0x95c4ce"
# green = "0xc0ca8e"
# magenta = "0xada0d3"
# red = "0xe98989"
# white = "0xd2d4de"
# yellow = "0xe9b189"
# 
# [colors.normal]
# black = "0x1e2132"
# blue = "0x84a0c6"
# cyan = "0x89b8c2"
# green = "0xb4be82"
# magenta = "0xa093c7"
# red = "0xe27878"
# white = "0xc6c8d1"
# yellow = "0xe2a478"
# 
# [colors.primary]
# background = "0x161821"
# foreground = "0x839496"

# monokai Pro
[colors.primary]
background = '0x2D2A2E'
foreground = '0xfff1f3'

[colors.normal]
black = '0x2c2525'
red = '0xfd6883'
green = '0xadda78'
yellow = '0xf9cc6c'
blue = '0xf38d70'
magenta = '0xa8a9eb'
cyan = '0x85dacc'
white = '0xfff1f3'

[colors.bright]
black = '0x72696a'
red = '0xfd6883'
green = '0xadda78'
yellow = '0xf9cc6c'
blue = '0xf38d70'
magenta = '0xa8a9eb'
cyan = '0x85dacc'
white = '0xfff1f3'

# [env]
# TERM = "alacritty"

[font]
size = 13.0
offset = { x = 0, y = 1 }
# glyph_offset = {x = 2, y = 2}

[font.bold]
# family = "Fira Code"
family = 'UDEV Gothic 35NFLG'
# family = 'Bizin Gothic Discord'
# family = 'Monaspace Neon'

[font.bold_italic]
# family = "Fira Code"
family = 'UDEV Gothic 35NFLG'
# family = 'Bizin Gothic Discord'
# family = 'Monaspace Neon'

[font.italic]
# family = "Fira Code"
family = 'UDEV Gothic 35NFLG'
# family = 'Bizin Gothic Discord'
# family = 'Monaspace Neon'

[font.normal]
# family = "Fira Code"
family = 'UDEV Gothic 35NFLG'
# family = 'Bizin Gothic Discord'
# family = 'Monaspace Neon'

[keyboard]
bindings = [
  { action = "ResetFontSize", key = "Key0", mods = "Super" },
  { action = "IncreaseFontSize", key = "=", mods = "Super" },
  { action = "DecreaseFontSize", key = "-", mods = "Super" },
  { action = "ClearHistory", key = "K", mods = "Super" },
  { action = "Paste", key = "V", mods = "Super" },
  { action = "Copy", key = "C", mods = "Super" },
  { action = "Hide", key = "H", mods = "Super" },
  { action = "Minimize", key = "M", mods = "Super" },
  { action = "Quit", key = "Q", mods = "Super" },
  { action = "Quit", key = "W", mods = "Super" },
  { action = "ToggleFullscreen", key = "F", mods = "Command|Control" },
  # { key = '[', mods= 'Alt', chars= "[" },
  # { key = 'H', mods= 'Alt', chars= "H" },
  # { key = 'J', mods= 'Alt', chars= "J" },
  # { key = 'K', mods= 'Alt', chars= "K" },
  # { key = 'L', mods= 'Alt', chars= "L" }
]

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`| =\"' ()[]{}<>\t"

[shell]
# program = "/bin/zsh"
program = "/usr/bin/fish"
# program = "/opt/homebrew/bin/tmux"
# args = ["-l", "-c", "tmux a || tmux"]
# args = [
#   "new-session",
#   "-A",
#   "-D",
#   "-s",
#   "default",
#   "source-file",
#   "~/.tmux.conf",
# ]

[window]
decorations = "full"
dynamic_padding = false
# startup_mode = "Windowed" | "Maximized" | "Fullscreen" | "SimpleFullscreen"
startup_mode = "Maximized"
opacity = 1.00
dynamic_title = true
option_as_alt = 'OnlyLeft'

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 0

[window.position]
x = 0
y = 0
